<#import "parts/common.ftlh" as c>

<@c.page>

<#--        <div>Hello, ${user.username}</div>-->
<#--        <span>  ${user.email}</span>-->
<#--        <span>  ${user.password}</span>-->

<h2>Тестовая платформа для администрирования пользователей </h2>
 <li>
     <ul>Админ панель</ul>
     <ul>Права</ul>
     <ul>Роли</ul>
     <ul>Добавление пользователей</ul>
     <ul>Удаление пользователей</ul>
     <ul>Редактирование пользователей</ul>
 </li>
</@c.page>
